# permissions for end users to edit cloudshells.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudshell-editor-role
rules:
- apiGroups:
  - cloudshell.daocloud.io
  resources:
  - cloudshells
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudshell.daocloud.io
  resources:
  - cloudshells/status
  verbs:
  - get
