# permissions for end users to view cloudshells.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudshell-viewer-role
rules:
- apiGroups:
  - cloudshell.daocloud.io
  resources:
  - cloudshells
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudshell.daocloud.io
  resources:
  - cloudshells/status
  verbs:
  - get
