apiVersion: cloudshell.cloudtty.io/v1alpha1
kind: CloudShell
metadata:
  name: vs-demo
  namespace: "cloudtty-system"
spec:
 configmapName: "my-kubeconfig"
 runAsUser: "root"
 commandAction: "bash"
 exposureMode: "VirtualService"
 pathPrefix: "/apis/cloudtty.io/"
 ttl: 100
 once: false
 virtualServiceConfig:
    virtualServiceName: "cloudshell-vs-demo"
    namespace: "cloudtty-system"
    gateway: "istio-system/istio-gateway"
    export_to: "istio-system"
