apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cloudtty.controllerManager.fullname" . }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - cloudshell.cloudtty.io
  resources:
  - cloudshells
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudshell.cloudtty.io
  resources:
  - cloudshells/finalizers
  verbs:
  - update
- apiGroups:
  - cloudshell.cloudtty.io
  resources:
  - cloudshells/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
